
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kotta
 */
public class admin_modifications extends javax.swing.JFrame {

    /**
     * Creates new form admin_modifications
     */
    public admin_modifications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eid = new javax.swing.JLabel();
        e_date_time = new javax.swing.JLabel();
        txename = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txevname = new javax.swing.JTextField();
        txevdate = new javax.swing.JTextField();
        txvenue = new javax.swing.JTextField();
        txjudge1 = new javax.swing.JTextField();
        txjudge2 = new javax.swing.JTextField();
        txfacnumber = new javax.swing.JTextField();
        txprize1 = new javax.swing.JTextField();
        txeid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txsponsor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        day1 = new javax.swing.JLabel();
        txday1 = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txcoordteamno1 = new javax.swing.JTextField();
        txprize2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Desktop\\dj.jpeg")); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Desktop\\dj.jpeg")); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Desktop\\djnight.jpeg")); // NOI18N
        jLabel14.setText("jLabel14");

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Desktop\\djnight.jpeg")); // NOI18N
        jLabel18.setText("jLabel18");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("          ADD EVENT ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 223, -1));

        eid.setBackground(new java.awt.Color(255, 255, 204));
        eid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eid.setForeground(new java.awt.Color(255, 255, 255));
        eid.setText("event id");
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, -1));

        e_date_time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        e_date_time.setForeground(new java.awt.Color(255, 255, 255));
        e_date_time.setText("event date");
        getContentPane().add(e_date_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, -1));

        txename.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txename.setForeground(new java.awt.Color(255, 255, 255));
        txename.setText("event name");
        getContentPane().add(txename, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("venue ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("judge 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("judge 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 150, -1));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("organizing faculty team number ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("prize1 ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("prize 2");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 110, 25));

        txevname.setBackground(new java.awt.Color(51, 51, 51));
        txevname.setForeground(new java.awt.Color(255, 255, 255));
        txevname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txevnameActionPerformed(evt);
            }
        });
        getContentPane().add(txevname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 210, -1));

        txevdate.setBackground(new java.awt.Color(51, 51, 51));
        txevdate.setForeground(new java.awt.Color(255, 255, 255));
        txevdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txevdateActionPerformed(evt);
            }
        });
        getContentPane().add(txevdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 220, -1));

        txvenue.setBackground(new java.awt.Color(51, 51, 51));
        txvenue.setForeground(new java.awt.Color(255, 255, 255));
        txvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txvenueActionPerformed(evt);
            }
        });
        getContentPane().add(txvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 220, -1));

        txjudge1.setBackground(new java.awt.Color(51, 51, 51));
        txjudge1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txjudge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 220, -1));

        txjudge2.setBackground(new java.awt.Color(51, 51, 51));
        txjudge2.setForeground(new java.awt.Color(255, 255, 255));
        txjudge2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txjudge2ActionPerformed(evt);
            }
        });
        getContentPane().add(txjudge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 220, -1));

        txfacnumber.setBackground(new java.awt.Color(51, 51, 51));
        txfacnumber.setForeground(new java.awt.Color(255, 255, 255));
        txfacnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfacnumberActionPerformed(evt);
            }
        });
        getContentPane().add(txfacnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 180, -1));

        txprize1.setBackground(new java.awt.Color(51, 51, 51));
        txprize1.setForeground(new java.awt.Color(255, 255, 255));
        txprize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txprize1ActionPerformed(evt);
            }
        });
        getContentPane().add(txprize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 220, -1));

        txeid.setBackground(new java.awt.Color(51, 51, 51));
        txeid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sponsor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 70, -1));

        txsponsor.setBackground(new java.awt.Color(51, 51, 51));
        txsponsor.setForeground(new java.awt.Color(255, 255, 255));
        txsponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txsponsorActionPerformed(evt);
            }
        });
        getContentPane().add(txsponsor, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 220, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ADD EVENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 130, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("yyyy-MM-dd HH:mm:ss format");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("enter the following details correctly");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        day1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        day1.setForeground(new java.awt.Color(255, 255, 255));
        day1.setText("day");
        getContentPane().add(day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        txday1.setBackground(new java.awt.Color(51, 51, 51));
        txday1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, -1));
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 720, 190, 20));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("co ordinating team number");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 260, -1));

        txcoordteamno1.setBackground(new java.awt.Color(51, 51, 51));
        txcoordteamno1.setForeground(new java.awt.Color(255, 255, 255));
        txcoordteamno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcoordteamno1ActionPerformed(evt);
            }
        });
        getContentPane().add(txcoordteamno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 230, -1));

        txprize2.setBackground(new java.awt.Color(51, 51, 51));
        txprize2.setForeground(new java.awt.Color(255, 255, 255));
        txprize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txprize2ActionPerformed(evt);
            }
        });
        getContentPane().add(txprize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 220, -1));

        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, -1));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, 180, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Budget");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, -1, -1));

        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Documents\\Cultural Fest Management images\\DjStage.jpg")); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -640, -1, 1870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txevnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txevnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txevnameActionPerformed

    private void txevdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txevdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txevdateActionPerformed

    private void txvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txvenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txvenueActionPerformed

    private void txjudge2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txjudge2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txjudge2ActionPerformed

    private void txfacnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfacnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfacnumberActionPerformed

    private void txprize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txprize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txprize1ActionPerformed

    private void txsponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txsponsorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txsponsorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    String query = "INSERT INTO event_details VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement ps = con.prepareStatement(query);
    ps.setString(1, txeid.getText());
    ps.setInt(2, Integer.parseInt(txday1.getText()));
    ps.setString(3, txevname.getText());
    String dateTimeString = txevdate.getText();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    java.util.Date dateTime = sdf.parse(dateTimeString);
    java.sql.Timestamp sqlTimestamp = new java.sql.Timestamp(dateTime.getTime());
    ps.setTimestamp(4, sqlTimestamp);
    ps.setString(5, txvenue.getText());
    ps.setString(6, txjudge1.getText());
    ps.setString(7, txjudge2.getText());
    ps.setInt(8, Integer.parseInt(txfacnumber.getText()));
    ps.setString(9, txprize1.getText());
    ps.setString(10, txprize2.getText());
    ps.setInt(11, Integer.parseInt(txcoordteamno1.getText()));
    ps.setString(12, txsponsor.getText());
    ps.setInt(13, Integer.parseInt(jTextField2.getText()));
    ps.executeUpdate();
    ps.close();
    con.close();
    JOptionPane.showMessageDialog(this,"Event Inserted SUCCESFULLY");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e);
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txcoordteamno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcoordteamno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcoordteamno1ActionPerformed

    private void txprize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txprize2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txprize2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Adminpage a=new Adminpage();
        a.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_modifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_modifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_modifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_modifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_modifications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel day1;
    private javax.swing.JLabel e_date_time;
    private javax.swing.JLabel eid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel result;
    private javax.swing.JTextField txcoordteamno1;
    private javax.swing.JTextField txday1;
    private javax.swing.JTextField txeid;
    private javax.swing.JLabel txename;
    private javax.swing.JTextField txevdate;
    private javax.swing.JTextField txevname;
    private javax.swing.JTextField txfacnumber;
    private javax.swing.JTextField txjudge1;
    private javax.swing.JTextField txjudge2;
    private javax.swing.JTextField txprize1;
    private javax.swing.JTextField txprize2;
    private javax.swing.JTextField txsponsor;
    private javax.swing.JTextField txvenue;
    // End of variables declaration//GEN-END:variables
}
