
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kotta
 */
public class charge_management extends javax.swing.JFrame {

    /**
     * Creates new form charge_management
     */
    public charge_management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        show_charge_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        update_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        show_selected_button = new javax.swing.JButton();
        update_selected_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, -1, -1));

        show_charge_button.setText("Show Charges");
        show_charge_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_charge_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(show_charge_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event id", "Event Name", "Budget"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 799, 127));

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Enter modifications to update in this table to update the budget of the event");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 462, 20));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter event id to get the details:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 300, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 193, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Event id", "Name", "Budget"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 778, 50));

        show_selected_button.setText("Show");
        show_selected_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_selected_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(show_selected_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        update_selected_button.setText("update this row");
        update_selected_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_selected_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(update_selected_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 589, 441, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Documents\\Cultural Fest Management images\\vfx4.jpeg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -9, 1480, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_charge_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_charge_buttonActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","root");
            Statement st=con.createStatement();
            String sql="select e_id,ename,budget from event_details";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new String[]{rs.getString(1),rs.getString(2),String.valueOf(rs.getInt(3))});
            }
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_show_charge_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
         try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String updateQuery = "UPDATE event_details SET budget=? WHERE e_id=?";
          java.sql.PreparedStatement st = con.prepareStatement(updateQuery);
    for (int i = 0; i < model.getRowCount(); i++) {
        String id = model.getValueAt(i, 0).toString();
        int budgeT=Integer.parseInt(model.getValueAt(i, 2).toString());
        st.setInt(1, budgeT);
        st.setString(2, id);
        
        st.addBatch();
    }
    st.executeBatch();
    JOptionPane.showMessageDialog(this, "Records updated successfully.");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_update_buttonActionPerformed

    private void show_selected_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_selected_buttonActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    String sq = "SELECT * FROM event_details WHERE e_id=?";
    PreparedStatement ps = con.prepareStatement(sq);
    ps.setString(1, jTextField1.getText());
    ResultSet rs = ps.executeQuery();
    if (!rs.next()) {
        jLabel3.setText("");
        JOptionPane.showMessageDialog(this, "Record not found.");

        
    } else {
        String query1 = "SELECT e_id, ename, budget from event_details WHERE e_id=?";
        PreparedStatement ps1 = con.prepareStatement(query1);
        ps1.setString(1, jTextField1.getText());
        rs = ps1.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        while (rs.next()) {
            model.addRow(new String[]{rs.getString(1), rs.getString(2), String.valueOf(rs.getInt(3))});
        }
        jLabel3.setText("Record Retrieved Succesfully");
      
    }
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}

               
    }//GEN-LAST:event_show_selected_buttonActionPerformed

    private void update_selected_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_selected_buttonActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    String updateQuery = "UPDATE event_details SET budget=? WHERE e_id=?";
          java.sql.PreparedStatement st = con.prepareStatement(updateQuery);
    for (int i = 0; i < model.getRowCount(); i++) {
        String id = model.getValueAt(i, 0).toString();
        int budgeT=Integer.parseInt(model.getValueAt(i, 2).toString());
        st.setInt(1, budgeT);
        st.setString(2, id);
        
        st.addBatch();
    }
    st.executeBatch();
      jLabel3.setText("");
    JOptionPane.showMessageDialog(this, "Records updated successfully.");
    
    Statement st1=con.createStatement();
            String sql="select * from event_details";
            ResultSet rs=st1.executeQuery(sql);
            DefaultTableModel model1=(DefaultTableModel)jTable1.getModel();
            model1.setRowCount(0);
            while(rs.next())
            {
                model1.addRow(new String[]{rs.getString(1),rs.getString(2),String.valueOf(rs.getInt(13))});
            }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_update_selected_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Adminpage a=new Adminpage();
        a.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(charge_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(charge_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(charge_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(charge_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new charge_management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton show_charge_button;
    private javax.swing.JButton show_selected_button;
    private javax.swing.JButton update_button;
    private javax.swing.JButton update_selected_button;
    // End of variables declaration//GEN-END:variables
}
