
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kotta
 */
public class Forgotpassword extends javax.swing.JFrame {

    /**
     * Creates new form Forgotpassword
     */
    public Forgotpassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tx1 = new javax.swing.JTextField();
        tx2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        passwordshow = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tx3 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 146, 46, -1));

        tx1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx1MouseClicked(evt);
            }
        });
        getContentPane().add(tx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 143, 146, -1));

        tx2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx2MouseClicked(evt);
            }
        });
        getContentPane().add(tx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 186, 146, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("security question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 189, 106, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Recover Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 93, 116, -1));
        getContentPane().add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 232, 41, -1));
        getContentPane().add(passwordshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 289, 146, -1));

        jButton1.setText("show Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 238, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 226, 41, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 328, 90, -1));
        getContentPane().add(tx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 325, 146, -1));

        jToggleButton1.setText("Login");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 407, 113, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Documents\\Cultural Fest Management images\\Djsinger2.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","root");
            String query="select * from user_details where id=?";
            java.sql.PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1,tx1.getText());
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                 String query1="select * from user_details where id= ? and security_que=?";
            java.sql.PreparedStatement ps1=con.prepareStatement(query1);
            ps1.setString(1,tx1.getText());
            ps1.setString(2,tx2.getText());
             ResultSet rs1=ps1.executeQuery();
             if(rs1.next())
             { 
               tx3.setText(rs1.getString(7));
             }
             else{
                 JOptionPane.showMessageDialog(null,"Security question is incorrect");
                
             }
            }
            else{
                JOptionPane.showMessageDialog(null,"user not there");
                tx1.setText("");
                tx2.setText("");
            }
            ps.close();
            con.close();
            
        }
        catch(Exception e){
            
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","root");
            String query="select * from user_details where id=?";
            java.sql.PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1,tx1.getText());
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                 String query1="select * from user_details where id= ? and password=?";
            java.sql.PreparedStatement ps1=con.prepareStatement(query1);
            ps1.setString(1,tx1.getText());
            ps1.setString(2,tx3.getText());
             ResultSet rs1=ps1.executeQuery();
             if(rs1.next())
             { 
              userhome w=new userhome(tx1.getText());
                w.show();
                dispose();  
             }
             else{
                 JOptionPane.showMessageDialog(null,"password incorrect");
             }
            }
            else{
                JOptionPane.showMessageDialog(null,"user not there");
                tx1.setText("");
                tx2.setText("");
            }
            ps.close();
            con.close();
            
        }
        catch(Exception e){
            
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void tx1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx1MouseClicked
        // TODO add your handling code here:
        tx3.setText("");
    }//GEN-LAST:event_tx1MouseClicked

    private void tx2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx2MouseClicked
        // TODO add your handling code here:
        tx3.setText("");
    }//GEN-LAST:event_tx2MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JLabel passwordshow;
    private javax.swing.JTextField tx1;
    private javax.swing.JTextField tx2;
    private javax.swing.JTextField tx3;
    // End of variables declaration//GEN-END:variables
}
