
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kotta
 */
public class Schedule_management extends javax.swing.JFrame {

    /**
     * Creates new form Schedule_management
     */
    public Schedule_management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Show Schedule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event id", "Event Name", "Date & Time", "Held on day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 867, 188));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 298, -1, -1));

        jLabel1.setText("Enter event id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 370, 85, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 367, 122, -1));

        jButton4.setText("Show");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 395, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event id", "Event Name", "Date& Time", "Held On Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 441, 867, 57));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 510, -1, -1));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 21, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Documents\\Cultural Fest Management images\\david-calderon-973699-unsplash.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-620, -1010, 2240, 2720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","root");
            Statement st=con.createStatement();
            String sql="select e_id,ename,edate_time,day from event_details";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                String dateTimeString = rs.getTimestamp(3).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date dateTime = sdf.parse(dateTimeString);
        String formattedDateTimeString = sdf.format(dateTime);
                model.addRow(new String[]{rs.getString(1),rs.getString(2),formattedDateTimeString ,String.valueOf(rs.getInt(4))});
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String updateQuery = "UPDATE event_details SET edate_time=?,day=? WHERE e_id=?";
    java.sql.PreparedStatement st = con.prepareStatement(updateQuery);
    for (int i = 0; i < model.getRowCount(); i++) {
        String id = model.getValueAt(i, 0).toString();
        int day=Integer.parseInt(model.getValueAt(i, 3).toString());
        String dateTimeString = model.getValueAt(i, 2).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date dateTime = sdf.parse(dateTimeString);
        Timestamp timestamp = new Timestamp(dateTime.getTime());
        st.setTimestamp(1, timestamp);
        st.setInt(2, day);
        st.setString(3, id);
        st.addBatch();
    }
    st.executeBatch();
    JOptionPane.showMessageDialog(this, "Records updated successfully.");
    Statement st1=con.createStatement();
            String sql="select * from event_details";
            ResultSet rs=st1.executeQuery(sql);
            DefaultTableModel model1=(DefaultTableModel)jTable1.getModel();
            model1.setRowCount(0);
            while(rs.next())
            {
                String dateTimeString = rs.getTimestamp(4).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date dateTime = sdf.parse(dateTimeString);
        String formattedDateTimeString = sdf.format(dateTime);
                
                model1.addRow(new String[]{rs.getString(1),rs.getString(3),formattedDateTimeString,String.valueOf(rs.getInt(2))});
            }
} 
catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    String sq = "SELECT * FROM event_details WHERE e_id=?";
    java.sql.PreparedStatement ps = con.prepareStatement(sq);
    ps.setString(1, jTextField1.getText());
    ResultSet rs = ps.executeQuery();
    if (!rs.next()) {
        JOptionPane.showMessageDialog(this, "Record not found.");

        
    } else {
        String query1 = "SELECT e_id, ename,edate_time,day from event_details WHERE e_id=?";
        java.sql.PreparedStatement ps1 = con.prepareStatement(query1);
        ps1.setString(1, jTextField1.getText());
        rs = ps1.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        while (rs.next()) {
             String dateTimeString = rs.getTimestamp(3).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            java.util.Date dateTime = sdf.parse(dateTimeString);
            String formattedDateTimeString = sdf.format(dateTime);

            model.addRow(new String[]{rs.getString(1), rs.getString(2),formattedDateTimeString, String.valueOf(rs.getInt(4))});
        }

      
    }
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
    String updateQuery = "UPDATE event_details SET edate_time=?,day=? WHERE e_id=?";
          java.sql.PreparedStatement st = con.prepareStatement(updateQuery);
    for (int i = 0; i < model.getRowCount(); i++) {
        String id = model.getValueAt(i, 0).toString();
        int d=Integer.parseInt(model.getValueAt(i, 3).toString());
        String dateTimeString = model.getValueAt(i, 2).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date dateTime = sdf.parse(dateTimeString);
        Timestamp timestamp = new Timestamp(dateTime.getTime());
        st.setTimestamp(1, timestamp);
        st.setInt(2, d);
        st.setString(3, id);
        
        st.addBatch();
    }
    st.executeBatch();
    JOptionPane.showMessageDialog(this, "Records updated successfully.");
    
    Statement st1=con.createStatement();
            String sql="select * from event_details";
            ResultSet rs=st1.executeQuery(sql);
            DefaultTableModel model1=(DefaultTableModel)jTable1.getModel();
            model1.setRowCount(0);
            while(rs.next())
            {
                  String dateTimeString = rs.getTimestamp(4).toString();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    java.util.Date dateTime = sdf.parse(dateTimeString);
                    String formattedDateTimeString = sdf.format(dateTime);
                model1.addRow(new String[]{rs.getString(1),rs.getString(3),formattedDateTimeString,String.valueOf(rs.getInt(2) )});
            }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Adminpage a=new Adminpage();
        a.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule_management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
