
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kotta
 */
public class updateProfile extends javax.swing.JFrame {

    /**
     * Creates new form updateProfile
     */
    public updateProfile( String u_id) {
  
        initComponents();
        id.setText(u_id);
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("show Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 63, 149, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "UserId", "Name", "Branch", "Year Of Study", "Email Id", "Phone Number", "Security Que"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 104, 939, 58));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 214, 140, -1));

        id.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 22, 115, 27));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 22, 75, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kotta\\Documents\\Cultural Fest Management images\\DjStage3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "root");
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Prepare the update statement
    String updateQuery = "UPDATE user_details SET name=?, branch=?, yos=?, emailid=?, phonenumber=?, security_que=? WHERE id=?";
    PreparedStatement st = con.prepareStatement(updateQuery);

    // Add the update statements to the batch
    for (int i = 0; i < model.getRowCount(); i++) {
        String id = model.getValueAt(i, 0).toString();
        String name = model.getValueAt(i, 1).toString();
        String branch = model.getValueAt(i, 2).toString();
        int yos = Integer.parseInt(model.getValueAt(i, 3).toString());
        String email = model.getValueAt(i, 4).toString();
        String phoneNumber = model.getValueAt(i, 5).toString();
        String securityQuestion = model.getValueAt(i, 6).toString();
        
        st.setString(1, name);
        st.setString(2, branch);
        st.setInt(3, yos);
        st.setString(4, email);
        st.setString(5, phoneNumber);
        st.setString(6, securityQuestion);
        st.setString(7, id);
        st.addBatch();
    }

    // Execute the batch update
    st.executeBatch();
    JOptionPane.showMessageDialog(this, "Records updated successfully.");

    // Retrieve the updated data from the database
    String selectQuery = "SELECT * FROM user_details WHERE id=?";
    PreparedStatement st2 = con.prepareStatement(selectQuery);
    DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
    String id = model1.getValueAt(0, 0).toString();
    st2.setString(1, id);
    ResultSet rs = st2.executeQuery();
    model1.setRowCount(0);
    while (rs.next()) {
        String name = rs.getString(2);
        String branch = rs.getString(3);
        int yos = rs.getInt(4);
        String email = rs.getString(5);
        String phoneNumber = rs.getString(6);
        String securityQuestion = rs.getString(7);
        model1.addRow(new String[]{id, name, branch, String.valueOf(yos), email, phoneNumber, securityQuestion});
    }

    // Close the database resources
    rs.close();
    st2.close();
    st.close();
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","root");
            String query="select * from user_details where id=?";
            java.sql.PreparedStatement ps=con.prepareStatement(query);
            String Id=id.getText();
            ps.setString(1,Id);
            ResultSet rs=ps.executeQuery();
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    while (rs.next()) {

        model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), String.valueOf(rs.getInt(4)),rs.getString(5), rs.getString(6), rs.getString(8)});
    }
    rs.close();
    ps.close();
    con.close();
         }catch(Exception e)
         {
            System.out.println(e);
            
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userhome u=new userhome(id.getText());
        u.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateProfile("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
